name: postrgres_idm

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_idm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_idm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: